services:
  server:
    build:
      context: .
      target: development
    ports:
      - "8080:8080"
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - MONGO_URL=mongodb://db:27017/${DB_NAME}
    volumes:
      - ./src:build/src
      - ./target:/build/target

  db:
    image: 'mongo:latest'
    restart: always
    volumes:
      - db-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-express:
    image: 'mongo-express:latest'
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=db

volumes:
  db-data:
