spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/${DB_NAME}-test
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}

logging:
  level:
    org:
      springframework:
        data:
          mongodb: DEBUG
