spring:
  application:
    name: MAJESTICCUP

  profiles:
    default: dev
    active:

---

logging:
  level:
    org:
      springframework:
        security: TRACE
        data:
          mongodb: DEBUG
